added default select option
irfanpule/django-form-surveys pull request #60
Opened 2023-06-04 03:30 UTC by GeekHamza1

2023-06-06 02:50 UTC, irfanpule requested changes
Halo @GeekHamza1 thank for your Pull Request.

2023-06-06 02:50 UTC, irfanpule commented on djf_surveys/forms.py
> +                default_choice = [("", "Sélectionner !")]
I think the variable name is more suitable for `empty_choice` because `default_choice` is more suitable for the choice set by the admin. So, please rename `default_choice` to `empty_choice`.

One more, please change `Selectionner` with english `Select` and then you can add translation.

2023-06-18 11:53 UTC, GeekHamza1 commented
its done

2023-06-19 03:46 UTC, irfanpule requested changes

2023-06-19 03:46 UTC, irfanpule commented on djf_surveys/forms.py
> +                choices = default_choice + choices
This line will cause an error because you haven't changed `default_choice`.

2023-06-19 03:46 UTC, irfanpule commented on djf_surveys/forms.py
> +                empty_choice = [("", "Select !")]
please string `Select` give func `gettext_lazy`.

```python
from django.utils.translation import gettext_lazy as _

...
empty_choice = [("", "_(Select)")]
...
```

2023-08-02 00:37 UTC, irfanpule commented
Hi @GeekHamza1 can you finish it?

2023-12-13 03:54 UTC, irfanpule commented
https://github.com/irfanpule/django-form-surveys/pull/64

I have finished at here

2023-12-13 03:54 UTC, closed without merging