Add option to change number of ratings
irfanpule/django-form-surveys pull request #71
Opened 2024-02-02 23:15 UTC by MartinK84

This rather complicated pull request adds the possibility to change the number of ratings used by adding a new "Number of ratings" property to rating questions:
![image](https://github.com/irfanpule/django-form-surveys/assets/50527612/5af86a2e-3e58-4631-8811-c5ab8f50b006)

Internally it simply stores the number of ratings in the ```choices``` property of the question model as this is was previously not used for rating questions. Simply reusing this property is IMO much simpler than creating a new model property just for the ratings.

The number of ratings displayed is then dynamically updated everywhere:
![image](https://github.com/irfanpule/django-form-surveys/assets/50527612/af15266b-b0da-4297-8b83-33c5652345cb)
![image](https://github.com/irfanpule/django-form-surveys/assets/50527612/09575797-dce9-452f-a0b9-0faadfa89113)

For future extensions one could think about storing json() encoded meta information in the choices field to bundle together more custom options - but I think that's a rather big change for future updates.

2024-02-03 05:00 UTC, irfanpule commented
Hi @MartinK84 
Thank for your PR. That is great update. I agree with you if use storing json() can be big change for the feature, so until now I don't think to change it. But I have plan for use storing json() to save option validation or anything each fields.

2024-02-03 05:30 UTC, irfanpule requested changes
That is great idea, but we must set max and min number of star. Because it wouldn't make sense if someone entered a value more than 10, for example 20 or 100.

2024-02-03 05:30 UTC, irfanpule commented on djf_surveys/admins/v2/forms.py
> +        self.fields['choices'].help_text = _("")
I think we must give info if user can only input  number 1 - 10. Maybe like this `You can enter number 1 - 10`

2024-02-03 05:30 UTC, irfanpule commented on djf_surveys/forms.py
> +                    validators=[MaxLengthValidator(len(str(int(question.choices)))), RatingValidator(int(question.choices))]
I think you don't need to change the `MaxLengthValidator` and `RatingValidator` to dynamic. Because max star just `10`, so you can set `MaxLenghtValidator(2)` and in `RatingValidator(10)`

2024-02-03 10:05 UTC, MartinK84 commented on djf_surveys/forms.py
> +                    validators=[MaxLengthValidator(len(str(int(question.choices)))), RatingValidator(int(question.choices))]
The idea was that the user has no way possible (maybe through modifying the HTML before the POST or the POST directly) to input any values that are larger than the individual limit that was set for the question. So if the limit for a question is set to 7 and the user tries to input an 8 it should IMO throw a validation error as it's validating against the limit of that question (7) and not against 10.

I agree that the chances for this happening are slim, but users could potentially distort rating results by entering values that are outside of the questions bounds (but still between 1 and 10).

2024-02-03 10:07 UTC, MartinK84 commented on djf_surveys/admins/v2/forms.py
> +        self.fields['choices'].help_text = _("")
Added in b7a1fcbed30ce4f12fcccf642f0371ef08d5ad45

2024-02-03 10:07 UTC, MartinK84 commented
I have also added another commit that changes the unit test to use ```RatingValidator()``` in case we stick with this (see discussion above), somehow missed this before, sorry

2024-02-03 10:28 UTC, MartinK84 commented
Regarding the long term change to store custom info per question as json(), I think it would be not that difficult to implement but  would break backward compatibility (or be a super huge headache with lots of code to keep it compatibly), so old installations/databases won't work anymore.

In the long run, however, I think this would be super useful as one could add a lot more options to the individual questions. 

For example for the rating questions I would like to add:
* the possibility to chose between different styles of the star (e.g. star vs. bullet)
* option to display labels at the lower and upper star (e.g. "1" next to the first star and "5" next to the last star)
* option to display custom labels next to the stars, same as before but with user defined custom text - so that one could write "poor" next to the first star or "excellent" next to the last star. That would be a great addition to make it clearer what is rated (which might different depending on the question).

For the ratings one could probably implement this by using the ```choices``` property of the model and just dump json() in there, but in the long run a more generic solution would be great :-)

2024-02-05 01:08 UTC, irfanpule commented
> I have also added another commit that changes the unit test to use `RatingValidator()` in case we stick with this (see discussion above), somehow missed this before, sorry

No worries, I missed too. Thank you

2024-02-05 01:18 UTC, irfanpule commented on djf_surveys/forms.py
> +                    validators=[MaxLengthValidator(len(str(int(question.choices)))), RatingValidator(int(question.choices))]
I see. Sorry I am misunderstanding about it. So to handle range input between 1 - 10, I think we must handle in clean at class `QuestionFormRatings`. CMIIW.

2024-02-05 01:33 UTC, irfanpule commented
> Regarding the long term change to store custom info per question as json(), I think it would be not that difficult to implement but would break backward compatibility (or be a super huge headache with lots of code to keep it compatibly), so old installations/databases won't work anymore.
> 
> In the long run, however, I think this would be super useful as one could add a lot more options to the individual questions.
> 
> For example for the rating questions I would like to add:
> 
> * the possibility to chose between different styles of the star (e.g. star vs. bullet)
> * option to display labels at the lower and upper star (e.g. "1" next to the first star and "5" next to the last star)
> * option to display custom labels next to the stars, same as before but with user defined custom text - so that one could write "poor" next to the first star or "excellent" next to the last star. That would be a great addition to make it clearer what is rated (which might different depending on the question).
> 
> For the ratings one could probably implement this by using the `choices` property of the model and just dump json() in there, but in the long run a more generic solution would be great :-)

Initially I created this module trying to keep it simple. Prioritize compatibility of all databases. But after developing until now, I also think about this. Maybe to maintain compatibility the model doesn't need to be initialized as a json field, maybe it could be a string of json stored in a textfield. For example like this:

```
class Question(BaseModel):
    ....
    extra_data = models.TextField()  # use to save custom property
```

The standard JSON data stored can vary depending on the field type requirements and then we don't have to change base model structure.

2024-02-05 07:24 UTC, MartinK84 commented
> Initially I created this module trying to keep it simple. Prioritize compatibility of all databases. But after developing until now, I also think about this. Maybe to maintain compatibility the model doesn't need to be initialized as a json field, maybe it could be a string of json stored in a textfield. For example like this:
> 
> ```
> class Question(BaseModel):
>     ....
>     extra_data = models.TextField()  # use to save custom property
> ```
> 
> The standard JSON data stored can vary depending on the field type requirements and then we don't have to change base model structure.

Just using a TextField() is also what I had in mind, this is super simple and you just have to slap a ```json.loads()``` and ```json.dumps()``` around it in code and then any type of question can use it in whatever way it likes to.

2024-02-05 19:06 UTC, MartinK84 commented on djf_surveys/forms.py
> +                    validators=[MaxLengthValidator(len(str(int(question.choices)))), RatingValidator(int(question.choices))]
You are correct, added this in e8397daf1aa175541d914d6dc5f8f1245864d4ba
Although I'm now very confused and not sure anymore what the validators in ```djf_surveys/forms.py``` above are actually used for? :-)

2024-02-06 01:47 UTC, irfanpule reviewed
Thank a lot

2024-02-06 01:47 UTC, irfanpule commented on djf_surveys/forms.py
> +                    validators=[MaxLengthValidator(len(str(int(question.choices)))), RatingValidator(int(question.choices))]
To match the help text. Prevent input that does not comply with the provisions.

2024-02-06 01:49 UTC, irfanpule approved these changes

2024-02-06 01:49 UTC, merged